---
name: Tests
on: push
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: ["5.2"]
    steps:
      - uses: actions/checkout@v2
      - name: Test ActiveRecord ${{ matrix.env }}
        run: docker-compose run -e AR_VERSION=${{ matrix.env }} test
